### ISSUE TITLE
Is there a way to make the columns more evenly spaced?

### ISSUE THREAD

**Issue by TheWyzer** [rabinnh/conky-stocks#1]
Hello, first thank you so much for this!

I am just curious if you know of a way to evenly space the columns so they are just "bunched"?  I am hoping that "outputs" can be put to a text file or another file type that "column" can work with?

Not sure how tough it would be to do that?  Columns already supports "`column Text.File -t -s`" so hopefully it can be done easily?

Maybe also add a color scheme for stock names?  Green for up, Red for down?

**Comment by rabinnh** [comment]
Using a monospaced font should line the columns up.  The sample "stocks" conky script uses "Ubuntu Mono".  If your system doesn't have that font it will use the default (likely not monospaced).

See if picking a mono-spaced font that you are sure is already on your system works and let me know.

**Comment by TheWyzer** [comment]
Thanks for that!  Using "ubuntu"  font for my conky so changed the Stocks to "ubuntu mono" and it spaces.  Sad thing is they aren't the same font, would have thought they were the same just one is "monospaced".

**Comment by TheWyzer** [comment]
Do you think it would be possible to add Crypto?
